### ISSUE TITLE
Unable to makeApplication

### ISSUE THREAD

**Issue by zhinuotech** [Monster-GM/NewBlackbox#2]
**Smartphone (please complete the following information):**
 - Device: oneplus6
 - OS: lineageos20 android13
 - Application wechat、jd、whatsapp、X

 
![1](https://github.com/Monster-GM/NewBlackbox/assets/119336855/753e9080-f860-4733-9c78-d9c81e06f717)

![image](https://github.com/Monster-GM/NewBlackbox/assets/119336855/ec1b1c2e-ec2b-4493-8699-98f98f6ebc25)

**Comment by zhinuotech** [comment]
vivo设备也不行 淘宝京东微信小红书抖音都打不开或者即使打开了也崩溃

**Comment by wordgege** [comment]
我遇到的问题和你的一致 我也是报这个错误请问你解决了吗

**Comment by wordgege** [comment]
我遇到的问题和你的一致 我也是报这个错误请问你解决了吗
